[package]
name = "rspass-core"
version = "0.2.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
dirs = { version = "5.0.1", optional = true }
git2 = "0.19.0"
pgp = "0.14.0"
rand = "0.8.5"
rsa = "0.9.6"

[features]
default = ["dirs"]
